### ISSUE TITLE
Configurable mount points

### ISSUE THREAD

**Issue by maehler** [gmc-norr/st2-analysis#21]
At the moment, the support for windows paths mounted on the unix systems partly hard-coded in the `win2unix` function in the sensor:
https://github.com/gmc-norr/st2-analysis/blob/413eefb97babd68fcce9b2f4292eb14686ad151b/sensors/tumor_evolution_sensor.py#L110-L114

A more flexible solution would be to have this being configurable. This way we can have arbitrary paths with arbitrary mounts. I'm thinking that the config could look something like this:

```yaml
win_path_mounts:
  - win: "G:\\Genetik"
    mnt: "/mnt/G-Genetik"
  - win: "K:\\Genetik"
    mnt: "/mnt/K-Genetik"
```
